### ISSUE TITLE
About the time required for training

### ISSUE THREAD

**Issue by robertjyh** [JinhuiYE/SignCL#1]
Thank you for sharing. When I trained the GFSLT-VLP model with the same number of GPUs(4 V100), my training time was much longer than what the original author said in https://github.com/zhoubenjia/GFSLT-VLP/issues/6.
I would like to know how long each of the two training stages takes when you use 8 GPUs for training?

**Comment by JinhuiYE** [comment]
Hi, we are happy to share.
In our case, we use 8*A800 GPUs for the two training stages. The pretraining takes about 12 hours for 80 epochs, but we have noticed it usually overfits before the 20th epoch, so you can use early stopping to save time. The finetuning stage takes approximately 14 hours.

**Comment by robertjyh** [comment]
Thank you for your reply! In addition, your paper does point out an important issue in SLT research.
